name: Build single extension

on:
  workflow_dispatch:
    inputs:
      lang:
        description: Extension language (en, ar, es, pt...)
        required: true
      extension:
        description: Target extension name
        required: true
      ismultisrc:
        type: boolean
        description: Its a multisrc extension
        default: false
        required: false
      git-repo:
        description: Git repo (Optional, defaults to <your name>/aniyomi-extensions
        default: ''
        required: false
      git-ref:
        description: Git Ref (Optional, defaults to master)
        default: 'master'
        required: false

env:
  BASEPATH: src
  EXTPATH: ${{ github.event.inputs.lang }}/${{ github.event.inputs.extension }}
  BASESLUG: individual
  EXTSLUG: ${{ github.event.inputs.lang }}:${{ github.event.inputs.extension }}
  REPO: ${{ github.event.inputs.git-repo }}
  CI_MODULE_GEN: true

jobs:
  build-extension:
    name: Build a single extension
    runs-on: ubuntu-latest
    steps:
      - name: Check inputs
        run: |
          set -e
          if [[ -z "${{ env.REPO }}" ]]; then
            echo "REPO=${{ github.repository_owner }}/aniyomi-extensions" >> $GITHUB_ENV
          fi
          if [[ ${{ github.event.inputs.ismultisrc }} != false ]]; then
            echo "BASEPATH=generated-src" >> $GITHUB_ENV
            echo "BASESLUG=multisrc" >> $GITHUB_ENV
          fi
      - name: Clone Repository (Latest)
        uses: actions/checkout@v3
        with:
          repository: ${{ env.REPO }}
          fetch-depth: 0
          ref: ${{ github.event.inputs.git-ref }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: adopt

      - name: Generate multisrc extensions
        if: ${{ github.event.inputs.ismultisrc == 'true' }}
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: :multisrc:multisrcGenerators
          gradle-home-cache-cleanup: true

      - name: Build APK
        uses: gradle/gradle-build-action@v2.3.3
        with:
          arguments: :extensions:${{ env.BASESLUG }}:${{ env.EXTSLUG }}:assembleDebug
          gradle-home-cache-cleanup: true

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{github.event.inputs.lang}}-${{ github.event.inputs.extension }}
          path: "${{ env.BASEPATH }}/${{ env.EXTPATH }}/build/outputs/apk/debug/*.apk"
          retention-days: 1